---
# Configuration to access VMs
ansible_user: "debian"
ansible_become: true
ansible_ssh_private_key_file: "~/.ssh/keys/ansible-test.pem"

# Configurations to create VMs
heat_stack_name: "udemy-ansible"
heat_groups:
  - db_servers
  - lb_servers
  - web_servers
heat_flavor: "flvC1M1D10"
heat_image: "debian-9.9.1"
heat_key_name: "ansible-test"
heat_network: "vlan175"
heat_api_version: 3

# Information about web external ip
web_external_ip: "{{hostvars[groups['lb_servers'][0]]['ansible_host']}}"
notification_subject: "Ansible Report - Web Application"
notification_body: >
  Hello!

  Ansible playbook for Udemy Ansible Assignment was executed.
  Go to http://{{ web_external_ip }} to access the web application.

  Thanks.

