---
- name: Create stack file
  template:
    src: stack.yml.j2
    dest: stack.yml
  register: stack
- name: Create stack
  os_stack:
    name: "{{heat_stack_name}}"
    state: present
    template: "stack.yml"
  when: stack is changed and heat_api_version!=3

  # os_stack doesn't work with identity_api_version 3
- name: Create stack
  shell: "openstack stack create -t stack.yml --wait {{heat_stack_name}}"
  environment:
    OS_AUTH_URL: "{{lookup('env', 'OS_AUTH_URL')}}"
    OS_PROJECT_ID: "{{lookup('env', 'OS_PROJECT_ID')}}"
    OS_PROJECT_NAME: "{{lookup('env', 'OS_PROJECT_NAME')}}"
    OS_USER_DOMAIN_NAME: "{{lookup('env', 'OS_USER_DOMAIN_NAME')}}"
    OS_USER_DOMAIN_ID: "{{lookup('env', 'OS_USER_DOMAIN_ID')}}"
    OS_USERNAME: "{{lookup('env', 'OS_USERNAME')}}"
    OS_PASSWORD: "{{lookup('env', 'OS_PASSWORD')}}"
    OS_REGION_NAME: "{{lookup('env', 'OS_REGION_NAME')}}"
    OS_INTERFACE: "{{lookup('env', 'OS_INTERFACE')}}"
    OS_IDENTITY_API_VERSION:  "{{lookup('env', 'OS_IDENTITY_API_VERSION')}}"
  when: stack is changed and heat_api_version==3
